link:
	ln -sf ../libraries/ArduinoJson/src/ArduinoJson ArduinoJson
	ln -sf ../libraries/ArduinoJson/src/ArduinoJson.h ArduinoJson.h
	ln -sf ../libraries/ArduinoJson/src/ArduinoJson.hpp ArduinoJson.hpp
	ln -sf ../libraries/Dash.ino/src/Dash.cpp Dash.cpp
	ln -sf ../libraries/Dash.ino/src/Dash.h Dash.h
	ln -sf ../libraries/aWOT/aWOT.cpp aWOT.cpp
	ln -sf ../libraries/aWOT/aWOT.h aWOT.h
	ln -sf ../libraries/hueDino/src/hueDino.cpp hueDino.cpp
	ln -sf ../libraries/hueDino/src/hueDino.h hueDino.h
	ln -sf ../libraries/hueDino/src/include include
